# Generated by Django 4.1.1 on 2022-09-22 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petclassiffier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodels',
            name='architecture',
            field=models.FileField(default=None, upload_to='mlmodels/'),
        ),
        migrations.AddField(
            model_name='mlmodels',
            name='description',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='mlmodels',
            name='priority',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mlmodels',
            name='title',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='mlmodels',
            name='weights',
            field=models.FileField(default=None, upload_to='mlmodels/'),
        ),
    ]
